# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

msf <- function(lambda, pivot) {
    .Call(`_infinitefactor_msf`, lambda, pivot)
}

msfOUT <- function(lambda, pivot) {
    .Call(`_infinitefactor_msfOUT`, lambda, pivot)
}

aplr <- function(matr, perm) {
    .Call(`_infinitefactor_aplr`, matr, perm)
}

update_Lambda_mgps <- function(Eta, X, sigma2_inv, Phi, tau) {
    .Call(`_infinitefactor_update_Lambda_mgps`, Eta, X, sigma2_inv, Phi, tau)
}

update_Lambda_dl <- function(Eta, X, sigma2_inv, Psi, Delta) {
    .Call(`_infinitefactor_update_Lambda_dl`, Eta, X, sigma2_inv, Psi, Delta)
}

update_Lambda_cusp <- function(Eta, X, sigma2_inv, theta) {
    .Call(`_infinitefactor_update_Lambda_cusp`, Eta, X, sigma2_inv, theta)
}

